trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/UnitTest1.cs'
  project: '**/playwrightDemo.csproj'

steps:
- pwsh: bin\Debug\netX\playwright.ps1 install --with-deps
  displayName: 'Install Playwright'

