trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/UnitTest1.cs'
  project: '**/playwrightDemo.csproj'

steps:
- pwsh: drop/tests/.playwright/node/win32_x64/playwright.cmd install
  displayName: 'Install Playwright'

